import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { createRuntime } from "../src/core/runtime.js";
import { silentLogger } from "../src/core/logger.js";
import { createMcpServer, SERVER_VERSION } from "../src/bridge/tools.js";
import { testConfig } from "./helpers.js";

const repo = path.resolve(import.meta.dirname, "..", "..");
const doc = (name: string) => readFileSync(path.join(repo, "docs", name), "utf8");

// docs/TOOLS.md is generated by `npm run docs`; this is what stops it rotting after a tool is added.
test("docs: TOOLS.md lists exactly the tools the server offers", async () => {
  const rt = await createRuntime({ config: testConfig({ executor: { kind: "node" } }), logger: silentLogger });
  const server = createMcpServer({ rt });
  const [a, b] = InMemoryTransport.createLinkedPair();
  const client = new Client({ name: "t", version: "1" });
  await Promise.all([server.connect(a), client.connect(b)]);
  try {
    const live = (await client.listTools()).tools.map((t) => t.name).sort();
    const text = doc("TOOLS.md");
    const documented = [...text.matchAll(/^\| `([a-z0-9_]+)`/gm)].map((m) => m[1]!).sort();
    const missing = live.filter((n) => !documented.includes(n));
    const stale = documented.filter((n) => !live.includes(n));
    assert.deepEqual({ missing, stale }, { missing: [], stale: [] }, "run `npm run docs`");
    assert.match(text, new RegExp(`ChatBridge ${SERVER_VERSION.replace(/\./g, "\\.")}`), "run `npm run docs` after bumping SERVER_VERSION");
    assert.match(text, new RegExp(`\\*\\*${live.length} 個工具\\*\\*`));
  } finally {
    await client.close();
    await rt.close();
  }
});

// Every CLI command in the help text should exist, and every command should be in the help text.
test("docs: the CLI help text and the dispatcher agree", () => {
  const src = readFileSync(path.join(repo, "src", "bridge", "cli.ts"), "utf8");
  const help = src.slice(src.indexOf("const HELP = `"), src.indexOf("const out ="));
  const dispatched = [...src.matchAll(/^    case "([a-z-]+)":/gm)].map((m) => m[1]!).filter((c) => !c.startsWith("-"));
  const undocumented = dispatched.filter((c) => !["help", "stdio", "up"].includes(c) && !help.includes(`chatbridge ${c}`));
  assert.deepEqual(undocumented, [], "these commands are missing from the help text");
});
